server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  mvc:
    hiddenmethod:
      filter:
        enabled: true

springdoc:
  swagger-ui:
    path: /api/swagger
