CREATE TABLE CATEGORY(
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(100)
);

INSERT INTO CATEGORY VALUES ('Pianino');
INSERT INTO CATEGORY VALUES ('Gitara');
INSERT INTO CATEGORY VALUES ('Wokal');
INSERT INTO CATEGORY VALUES ('Perkusja');